spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: 'hoamanager'
  datasource:
    url: 'jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'